//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod person;
pub mod person_document_type;
pub mod person_gender;
pub mod product;
pub mod product_family;
pub mod user;
