//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::person::Entity as Person;
pub use super::person_document_type::Entity as PersonDocumentType;
pub use super::person_gender::Entity as PersonGender;
pub use super::product::Entity as Product;
pub use super::product_family::Entity as ProductFamily;
pub use super::user::Entity as User;
